import path from 'path';
import { DEFAULT_BASE_PATH } from './node-utils';
import {
  FIREBASE_CONFIG_FILE_NAME,
  DEFAULT_TEST_FOLDER_PATH,
  DEFAULT_CONFIG_FILE_NAME,
  DEFAULT_TEST_ENV_FILE_NAME,
  DEFAULT_TEST_CONFIG_FILE_NAME,
} from './constants';

export const FIREBASE_CONFIG_FILE_PATH = path.join(
  DEFAULT_BASE_PATH,
  FIREBASE_CONFIG_FILE_NAME,
);
export const TEST_CONFIG_FILE_PATH = path.join(
  DEFAULT_BASE_PATH,
  DEFAULT_TEST_CONFIG_FILE_NAME,
);
export const TEST_ENV_FILE_PATH = path.join(
  DEFAULT_BASE_PATH,
  DEFAULT_TEST_ENV_FILE_NAME,
);
export const LOCAL_CONFIG_FILE_PATH = path.join(
  DEFAULT_BASE_PATH,
  DEFAULT_TEST_FOLDER_PATH,
  DEFAULT_CONFIG_FILE_NAME,
);
